common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    # path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    # path('login/', auth_views.LoginView.as_view(), name='login'),
    path('login/', views.signin, name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
    path('domain/', views.domain_list, name='domain_list'),
    path('url/', views.url, name='url'),
    path('url/create/', views.url_create, name='url_create'),
    path('url/delete/<int:pk>', views.url_delete, name='url_delete'),
    path('url/edit/<int:pk>', views.url_edit, name='url_edit'),
    path('domain/create', views.domain_create, name='domain_create'),
    path('domain/delete/<int:pk>', views.domain_delete, name='domain_delete'),
    path('domain/verify/<int:pk>', views.domain_verify, name='domain_verify'),   
]

handler404 = 'common.views.page_not_found'

config/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('_django_admin_/', admin.site.urls),
    path('_common_/', include('common.urls')),
    path('', include('shorty.urls')),
]

handler404 = 'common.views.page_not_found'

shorty/urls.py
from . import views
from django.urls import path

app_name = 'shorty'

urlpatterns = [
    path('<str:alias>/', views.surl, name='alias'),
    path('',views.index, name='index' ),
]

common/models.py
from django.db import models

# Create your models here.

common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserForm(UserCreationForm):
    email = forms.EmailField(label='이메일')
    
    class Meta:
        model = User
        fields = ("username", "password1", "password2", "email")
    
    

common/views.py
from datetime import timedelta
from django.conf import settings 
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ValidationError
from django.shortcuts import render, redirect, HttpResponse, get_object_or_404
from django.utils import timezone
from common.forms import UserForm
from shorty.forms import SurlForm,DomainForm
from shorty.models import Domain,Surl
from pathlib import Path
from random import randint,shuffle


import environ
import json
import logging
import urllib.request
import urllib.parse


logger=logging.getLogger('shorty')
BASE_DIR = Path(__file__).resolve().parent.parent.parent
env = environ.Env()
environ.Env.read_env(BASE_DIR / '.env')
SSL_LIST = env('SSL_LIST')


# Create your views here.

def signin(request):
    
    if request.user.is_authenticated:
        return redirect('common:url')
    
    if request.method == "POST":
        
        result = recaptcha_result(request)
        
        if result['success']:
        
            username = request.POST['username']
            password = request.POST['password']
            
            user = authenticate(request,username=username,password=password)
            
            if user is not None:
                messages.success(request, '로그인 성공')
                login(request, user)
                return redirect('common:url')
            
            else:
                messages.error(request, '아이디 혹은 비밀번호가 올바르지 않습니다.')
                
        else:
            messages.error(request, "reCAPTCHA가 완료되지 않았습니다. 확인 후 다시 시도하세요.")
    
    return render(request, 'common/login.html')
    

def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)

        # ''' Begin reCAPTCHA validation '''
        result = recaptcha_result(request)
        # ''' End reCAPTCHA validation '''

        if result['success']:
            if form.is_valid():
                form.save()
                username = form.cleaned_data.get('username')
                raw_password = form.cleaned_data.get('password1')
                user = authenticate(username=username, password=raw_password)
                login(request, user)
                messages.success(request,"가입 완료")
                return redirect('common:url')
            
        else:
            messages.error(request, 'reCAPTCHA가 완료되지 않았습니다. 확인 후 다시 시도하세요.')

        
        # if form.is_valid():
        #     form.save()
        #     username = form.cleaned_data.get('username')
        #     raw_password = form.cleaned_data.get('password1')
        #     user = authenticate(username=username, password=raw_password)
        #     login(request, user)
        #     return redirect('common:url')

    else:
        form = UserForm()
        
    return render(request, 'common/signup.html', {'form':form})


def page_not_found(request, exception):
    return render(request, 'common/404.html', {})

@login_required(login_url='common:login')
def domain_list(request):
    
    # if request.method == "GET":
    if request.user.is_authenticated:
        domains = Domain.objects.filter(owner__username=request.user.username)
        context = {'domains':domains}
        return render(request,'common/domain.html',context=context)    

    else:
        return render(request,'shorty/index.html')    

@login_required(login_url='common:login')    
def url(request):
    if request.method == "GET":
        if request.user.is_authenticated:
            domains,surls = get_owned_objects(request)
            surls=surls.order_by('-visit_counts')
            form = SurlForm()
            
            
            # get wc data
            wc_data, colors = get_url_wc_data(surls)
                                    
            context = {'surls':surls,'domains':domains, 'form':form, 'wc_data':wc_data, 'colors':colors}
            return render(request,'common/url.html',context=context)    

        else:
            return render(request,'common/url.html')    

@login_required(login_url='common:login')    
def url_create(request):
    
    if request.user.is_authenticated:
        if request.method == "POST":
            form = SurlForm(request.POST)
            print(form)
            if form.is_valid() :
                print('form is valid')
                surl = form.save(commit=False)
                surl.domain = Domain.objects.get(name=form.cleaned_data['domain'])
                surl.short_url = str(surl.domain.name)+"/"+(surl.alias)
                try:
                    surl.validate_unique()
                    surl.save()
                                    
                except ValidationError as e:
                    domains, surls = get_owned_objects(request)
                    context = {'surls':surls,'domains':domains, 'form':form, 'e':e}
                    return render(request,'common/url.html',context=context)    
                
            else:
                domains, surls = get_owned_objects(request)
                context = {'surls':surls,'domains':domains, 'form':form}
                return render(request,'common/url.html',context=context)    
   
        return redirect('common:url')
    
    return HttpResponse('url created.')

def get_owned_objects(request):
    domains = Domain.objects.filter(owner__username=request.user.username)
    surls = Surl.objects.filter(domain__in=domains)
    surls=surls.order_by('-visit_counts')
    return domains,surls

@login_required(login_url='common:login')
def url_delete(request,pk):
    
    if request.user.is_authenticated:
        surl=Surl.objects.get(pk=pk)
        if surl.domain.owner.username == request.user.username:
            # 소유 여부 추가
            surl.delete()
            
        else:
            messages.error(request, "내 소유의 주소만 삭제가 가능합니다.")
            return render(request,'common/url.html')    

    return redirect('common:url')

@login_required(login_url='common:login')
def url_edit(request,pk):
    if request.user.is_authenticated:
        surl=Surl.objects.get(pk=pk)
        if surl.domain.owner.username == request.user.username:
            if request.method == "POST":
                form = SurlForm(request.POST,instance=surl)
                if form.is_valid() :
                    surl = form.save(commit=False)
                    surl.domain = Domain.objects.get(name=form.cleaned_data['domain'])
                    surl.short_url = str(surl.domain.name)+"/"+(surl.alias)
                    try:
                        surl.validate_unique()
                        surl.save()
                        messages.success(request,f"URL {surl.short_url}이 변경되었습니다.")
                        return redirect('common:url')
                                        
                    except ValidationError as e:
                        domains, surls = get_owned_objects(request)
                        context = {'surls':surls,'domains':domains, 'form':form, 'e':e, 'surl':surl}
                        messages.error(request,"중복된 주소가 존재합니다.")
                        return render(request,'common/url.html',context=context)    
                    
            else:
                form = SurlForm(instance=surl)
                domains, surls = get_owned_objects(request)
                
                wc_data, colors = get_url_wc_data(surls)
                context = {'surls':surls,'domains':domains, 'form':form, 'surl':surl, 'wc_data':wc_data, 'colors':colors}
                return render(request,'common/url.html',context=context)    
    
            return redirect('common:url')
            
        else:
            messages.error(request,"내 소유의 주소만 편집이 가능합니다.")
            return render(request,'common/url.html')    

    return redirect('common:url')    


@login_required(login_url='common:login')
def domain_create(request):
    
    if request.user.is_authenticated:
        if request.method == "POST":
            form = DomainForm(request.POST)
            print(form)
            if form.is_valid() :
                print('form is valid')
                domain = form.save(commit=False)
                domain.name = form.cleaned_data['name']
                domain.dns_txt = domain.create_dns_txt()
                domain.owner = request.user
                domain.host_allowed = False
                domain.save()
                return redirect('common:domain_list')
                                    
            else:
                domains, surls = get_owned_objects(request)
                context = {'domains':domains, 'form':form}
                return render(request,'common/domain.html',context=context)    
    
    else:
        return HttpResponse("login required")
    
@login_required(login_url='common:login')
def domain_verify(request,pk):
    if request.user.is_authenticated:
        domain = Domain.objects.get(pk=pk)
        if domain.owner.username == request.user.username:

            verification = domain.verify_ownership()
            if verification == 0:
                domain.is_verified = True
                domain.last_ownership_check = timezone.now()
                domain.dns_txt = None
                domain.save()
                
                with open(SSL_LIST, "a") as f:
                    f.write(f"{domain.name}\n")
                                
                return redirect('common:domain_list')
            
            elif verification == 1:
                # retry, time limit
                print(domain.VERIFY_INTERVAL)

                to_retry=domain.last_ownership_check + timedelta(seconds=Domain.VERIFY_INTERVAL) - timezone.now()
                messages.error(request,f"{to_retry.seconds:,}초 뒤에 다시 시도하세요.")
                domains = Domain.objects.filter(owner__username=request.user.username)
                context = {'domains':domains}
                

templates/common/domain.html
{% extends 'base.html' %}

{% block content %}
{% include "common/domain_form.html" %}

<div class="container my-3">
<table class="table table-hover">
    <thead>
        <tr>
            <th scope="col">Name</th>
            <th scope="col"></th>
            <th scope="col">Stauts</th>
            <th scope="col">Action</th>
          </tr>
    </thead>
    <tbody>
    {% for domain in domains %}
    <tr>
    <td><p class="text-body">{{ domain.name }}</p></td>
    
    <td>
        {% if not domain.is_verified %}
        <div class="spinner-border text-warning float-end spinner-border-sm" role="status">
            <span class="visually-hidden">Loading...</span>
        </div>

    {% endif %}
    </td>

    <td>
        {% if domain.is_verified %}
        <p class="text-success">Verified</p>
        {% else %}
        <p class="text-danger">{{ domain.dns_txt }}</p>
        {% endif %}
    </td>
    <td>        
        <div class="btn-group" role="group" aria-label="Basic mixed styles example">
            {% if domain.is_verified %}
            {% else %}
            <a class="btn btn-warning btn-sm" href="{% url 'common:domain_verify' pk=domain.pk %}">Verify</a>
            {% endif %}

            {% comment %}            
            <a class="btn btn-danger btn-sm" href="{% url 'common:domain_delete' pk=domain.pk %}">Delete</a>
            {% endcomment %} 
            
            <!-- Button trigger modal -->
            <button type="button" class="btn btn-danger btn-sm" data-bs-toggle="modal" data-bs-target="#staticBackdrop" data-bs-delete-url="{% url 'common:domain_delete' pk=domain.pk %}" data-bs-domain-name="{{ domain.name }}">
                Delete
            </button>

        </div>
    </td>

    </tr>
    {% endfor %}
</tbody>
</table>
</div>


        <!-- Modal -->
        <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
            <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                <h5 class="modal-title" id="staticBackdropLabel"></h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <p></p>
                </div>
                <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                <a class="btn btn-danger">Delete</a>
                </div>
            </div>
            </div>
        </div>

<!-- modal script -->


{% endblock %}

{% block script %}

<script type="text/javascript">
    var staticBackdrop = document.getElementById('staticBackdrop')
    staticBackdrop.addEventListener('show.bs.modal', function (event) {
      // Button that triggered the modal
      var button = event.relatedTarget
      // Extract info from data-bs-* attributes
      var domain_delete_url = button.getAttribute('data-bs-delete-url')
      var domain_name = button.getAttribute('data-bs-domain-name')
      // If necessary, you could initiate an AJAX request here
      // and then do the updating in a callback.
      //
      // Update the modal's content.
      var modalTitle = staticBackdrop.querySelector('.modal-title')
      var modalBody = staticBackdrop.querySelector('.modal-body p')
      var modalDeleteBtn = staticBackdrop.querySelector('.btn.btn-danger')
    
      modalTitle.textContent = 'Deleting ' + domain_name
      modalBody.textContent = '정말로 '+ domain_name +'을 삭제하시겠습니까? 해당 도메인과 연결된 모든 URL이 함께 삭제됩니다.'
      modalDeleteBtn.setAttribute('href',domain_delete_url)
    })
    </script>
{% endblock %}

templates/common/domain_form.html
<div class="container">
    <h5 class="my-3 border-bottom pb-2">Domain 등록</h5>
    <form method="post" action="{% url 'common:domain_create'%}">
        {% csrf_token %}

        <!-- 오류 표시 -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
        {% for field in form %}
            {% if field.errors %}
                <div>
                    <strong> {{ field.label }} </strong>
                    {{ field.errors }}
                </div>
            {% endif %}
        {% endfor %}
    </div>
    {% endif %}

    {% if e %}
        <div class="alert alert-danger" role="alert">
            <div class="mb-1">
                <strong> {{ e.messages.0 }} </strong>
           </div>
        </div>
    {% endif %}

    {% if err %}
        <div class="alert alert-danger" role="alert">
            <div class="mb-1">
                <strong> {{ err }} </strong>
           </div>
        </div>
    {% endif %}

    <!-- 오류 표시 End-->

    <div class="input-group mb-3 w-50">
        <input type="text" class="form-control" name="name" id="name" value="{{ form.domain.value|default_if_none:'' }}" placeholder="example.com">
    </div>
        <button class="btn btn-primary" type="submit">저장하기</button>
    </form>
</div>

templates/common/error.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-12 text-center">
            <span class="display-1 d-block">{{ err.code }}</span>
            <div class="mb-4 lead">{{ err.message }}</div>
            <a href="/" class="btn btn-link">홈으로 돌아가기</a>
        </div>
    </div>
</div>
{% endblock %}

templates/common/login.html
{% extends 'base.html' %}

{% block content %}
<div class="container my-3">
    <form method="post" action="{% url 'common:login' %}">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}">
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="username">사용자 ID</label>
            <input type="text" class="form-control" name="username" id="username" value="{{ form.username.value|default_if_none:'' }}">
        </div>

        <div class="mb-3">
            <label for="password">비밀번호</label>
            <input type="password" class="form-control" name="password" id="password" value="{{ form.password.value|default_if_none:'' }}">
        </div>

        <div class="mb-3">
            <div class="g-recaptcha" data-sitekey="6LfDzX0oAAAAAC40jAti4OFhRO_HJ45MawM1bz6D" data-callback="recaptcha"></div>
        </div>


        <button class="btn btn-primary" type="submit">로그인</button>
    </form>
</div>

{% endblock %}

{% block script %}
<script src="https://www.google.com/recaptcha/api.js" async defer></script>
{% endblock %}

templates/common/signup.html
{% extends "base.html" %}
{% block content %}

<div class="container my-3">
    <form method="post" action="{% url 'common:signup' %}">
        {% csrf_token %}
        {% include "form_errors.html" %}
        
        <div class="mb-3">
            <label for="username">사용자 이름</label>
            <input type="text" class="form-control" name="username" id="username" value="{{ form.username.value|default_if_none:'' }}">
        </div>

        <div class="mb-3">
            <label for="password1">비밀번호</label>
            <input type="password" class="form-control" name="password1" id="password1" >
        </div>

        <div class="mb-3">
            <label for="password2">비밀번호 확인</label>
            <input type="password" class="form-control" name="password2" id="password2" >
        </div>

        <div class="mb-3">
            <label for="email">이메일</label>
            <input type="text" class="form-control" name="email" id="email" value="{{ form.email.value|default_if_none:'' }} ">
        </div>


        <div class="mb-3">
            <div class="g-recaptcha" data-sitekey="6LfDzX0oAAAAAC40jAti4OFhRO_HJ45MawM1bz6D" data-callback="recaptcha"></div>
        </div>

        <button type="submit" class="btn btn-primary">가입하기</button>

    </form>
</div>
{% endblock %}



{% block script %}
<script src="https://www.google.com/recaptcha/api.js" async defer></script>
{% endblock %}

templates/common/url.html
{% extends 'base.html' %}
{% load humanize %}

{% block content %}

<div class="container my-3">
    <div class="row">
      <div class="col">
        {% include "common/url_form.html" %}
      </div>
      <div class="col">
        <div class="my-5">
        {% include 'word_cloud.html' %}
        </div>
        </div>
    </div>
</div>






<div class="container my-3">

            <table class="table table-hover table-bordered">
                <thead>
                    <tr>
                        <th scope="col" class="text-center">Short URL</th>
                        <th scope="col" class="text-center">Visit counts</th>
                        <th scope="col" class="text-center">URL</th>
                        <th scope="col" class="text-center">Note</th>
                        <th scope="col" class="text-center">Action</th>
                    </tr>
                </thead>
                <tbody>
                {% for surl in surls %}
                <tr>
                <td>{{ surl.short_url }}</td>
                <td class="text-end">{{ surl.visit_counts|intcomma }}</td>
                <td style="word-break:break-all"><a href="{{ surl.url }}" class="link-secondary" target="_blank" rel="noopener noreferrer">{{ surl.url }}</a></td>
                <td>{{ surl.note }}</td>
                <td class="text-center">

                                <a class="btn btn-secondary btn-sm" href="{% url 'common:url_edit' pk=surl.id %}">수정</a>
                                <a class="btn btn-danger btn-sm" href="{% url 'common:url_delete' pk=surl.id %}">삭제</a>
                </td>
                </tr>
                {% endfor %}
                </tbody>
                </table>

</div>

   


{% endblock %}
{% block script %}
<script type="text/javascript">
    const page_elements = document.getElementsByClassName("page-link");
    Array.from(page_elements).forEach(function(element) {
        element.addEventListener("click", function(){
        document.getElementById("page").value = this.dataset.page;
        document.getElementById("searchForm").submit();
        });
    });

    const btn_search = document.getElementById("btn_search");
    btn_search.addEventListener("click", function() {
        document.getElementById('kw').value = document.getElementById("search_kw").value;
        document.getElementById("page").value = 1;
        document.getElementById("searchForm").submit();
    });

    const inputbox_search_kw = document.getElementById("search_kw");
    inputbox_search_kw.addEventListener("keypress", function(e) {
        if(e.keyCode == 13){
            document.getElementById('kw').value = document.getElementById("search_kw").value;
            document.getElementById("page").value = 1;
            document.getElementById("searchForm").submit();
            }
    });

</script>
{% endblock %}

templates/common/url_form.html
<div class="container my-3">



    {% if "/_common_/url/edit/" in request.path %}
    <h5 class="my-3 border-bottom pb-2"><mark>URL 수정</mark></h5>
    <form method="post" action="{% url 'common:url_edit' pk=surl.id %}">
    
    {% else %}
    <h5 class="my-3 border-bottom pb-2">URL 등록</h5>
    <form method="post" action="{% url 'common:url_create' %}">
    {% endif %}

            {% csrf_token %}

            <!-- 오류 표시 -->
            {% if form.errors %}
            <div class="alert alert-danger" role="alert">
            {% for field in form %}
                {% if field.errors %}
                    <div>
                        <strong> {{ field.label }} </strong>
                        {{ field.errors }}
                    </div>
                {% endif %}
            {% endfor %}
        </div>
        {% endif %}

        {% if e %}
            <div class="alert alert-danger" role="alert">
                <div class="mb-1">
                    <strong> {{ e.messages.0 }} </strong>
            </div>
            </div>
        {% endif %}
    <!-- 오류 표시 End-->
    
            <div class="input-group mb-3">
                <select class="form-select" aria-label="Domain selection" name="domain" id="domain">
                        <option>Select domain</option>
                        {% for domain in domains %}
                            {% if domain.is_verified %}
                                {% if form.domain.value|add:"0" == domain.id %}
                                    <option value="{{ domain.id }}" selected>{{ domain.name }}</option>
                                {% else %}
                                    <option value="{{ domain.id }}">{{ domain.name }}</option>
                                {% endif %}
                            {% endif %}
                        {% endfor %}
                </select>
                <span class="input-group-text">/</span>
                <input type="text" class="form-control" name="alias" id="alias" value="{{ form.alias.value|default_if_none:'' }}" placeholder="alias">
            </div>
            <div class="input-group mb-3">

                <input type="text" class="form-control" name="url" id="url" value="{{ form.url.value|default_if_none:'' }}" placeholder="URL">
            </div>
            <div class="input-group mb-3">

                <input type="text" class="form-control" name="note" id="note" value="{{ form.note.value|default_if_none:'' }}" placeholder="Note">

            </div>

            <button class="btn btn-primary" type="submit">저장하기</button>
        </form>
</div>