common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    # path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    # path('login/', auth_views.LoginView.as_view(), name='login'),
    path('login/', views.signin, name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
    path('domain/', views.domain_list, name='domain_list'),
    path('url/', views.url, name='url'),
    path('url/create/', views.url_create, name='url_create'),
    path('url/delete/<int:pk>', views.url_delete, name='url_delete'),
    path('url/edit/<int:pk>', views.url_edit, name='url_edit'),
    path('domain/create', views.domain_create, name='domain_create'),
    path('domain/delete/<int:pk>', views.domain_delete, name='domain_delete'),
    path('domain/verify/<int:pk>', views.domain_verify, name='domain_verify'),   
]

handler404 = 'common.views.page_not_found'

config/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('_django_admin_/', admin.site.urls),
    path('_common_/', include('common.urls')),
    path('', include('shorty.urls')),
]

handler404 = 'common.views.page_not_found'

shorty/urls.py
from . import views
from django.urls import path

app_name = 'shorty'

urlpatterns = [
    path('<str:alias>/', views.surl, name='alias'),
    path('',views.index, name='index' ),
]

templates/base.html
{% load static %}
<!doctype>
<html lang="ko">
    <head>
        <!-- required meta tag -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- bootstrap CSS -->
        <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
        
        <!-- pybo CSS -->
        <title>Shorty</title>


		<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-5004947987319439" crossorigin="anonymous"></script>

    </head>
    <body>
    <!-- Navigation 삽입-->
    {% include "navbar.html" %}
    {% include "message.html" %}
    
    <!-- 기본 템플릿 안에 삽입될 내용 Start -->
    {% block content %}
    {% endblock %}
    <!-- 기본 템플릿 안에 삽입될 내용 End -->
    <!-- bootstrap JS -->
    <script src="{% static 'bootstrap.min.js' %}"></script>
    <script src="{% static 'bootstrap.bundle.min.js' %}"></script>

    <!-- jQuery scripts -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    <!-- 스크립트 -->
    {% block script %}
    {% endblock %}


    </body>
</html>

templates/form_errors.html
<!-- 필드 오류와 넌필드 오류를 출력 -->

{% if form.errors %}
<div class="alert alert-danger">
    {% for field in form %}
    {% if field.errors %}
    <!-- 필드 에러 -->
    <div>
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
    </div>
    {% endif %}
    {% endfor %}

<!-- 넌필드 오류 -->
    {% for error in form.non_field_errors %}
    <div>
        <strong>{{ error }}</strong>
    </div>
    {% endfor %}
</div>
{% endif %}

templates/message.html
<div class="container my-3">
{% for message in messages %}

    <div class="alert {{ message.tags }} alert-auto-dismissible alert-dismissible notification-container" role="alert">
        <!-- <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button> -->
        {{ message }}
    </div>
{% endfor %}
</div>

<script>
    window.setTimeout(function() {
        $(".alert-auto-dismissible").fadeTo(500, 0).slideUp(500, function(){
            $(this).remove();
        });
    }, 4000);
</script>

templates/navbar.html
<!-- Navigation bar -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'shorty:index' %}">Shorty</a>
        <button class="navbar-toggler" type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarSupportedContent"
            aria-bs-controls="navbarSupportedContent"
            aria-expanded="false"
            aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'common:domain_list' %}"> Domains</a>
                </li>
                <li class="nav-item">
                        <a class="nav-link" href="{% url 'common:logout' %}"> {{ user.username }} (로그아웃)</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'common:signup' %}">회원가입</a>
                </li>
                {% endif %}

            </ul>
        </div>

    </div>
</nav>

templates/word_cloud.html
<style>
      
      ul.cloud {
        list-style: none;
        padding-left: 0;
        display: flex;
        flex-wrap: wrap;
        align-items: center;
        justify-content: center;
        /* line-height: 2.75rem; */
        width: 450px;
        font-family: 'Arial', sans-serif;
        padding: 0;
        margin: 0;
      }
      
      ul.cloud a {
        /*   
        Not supported by any browser at the moment :(
        --size: attr(data-weight number); 
        */
        --size: 4;
        --color: #a33;
        color: var(--color);
        font-size: calc(var(--size) * 0.2rem + 0.3rem);
        display: block;
        padding: 0.125rem 0.25rem;
        position: relative;
        text-decoration: none;
        /* 
        For different tones of a single color
        opacity: calc((15 - (9 - var(--size))) / 15); 
        */
        opacity: calc((15 - (9 - var(--size))) / 15); 
        border-radius: 0.25rem;
        transition: all 0.3s ease;
      }


      {% for color in colors %}
      ul.cloud a[data-weight="{{ forloop.counter }}"]:hover {
        z-index:  100;
        transform: scale(1.2);
        background-color:{{ color }};
        color: #ffffff;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1); 
        animation: vibration 0.1s infinite;
        }
      {% endfor %}

      /*
      ul.cloud a:hover {
        transform: scale(1.1);
        background-color: #3498db;
        color: #ffffff;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        
    }*/

      {% for color in colors %}
      ul.cloud a[data-weight="{{ forloop.counter }}"] { --size: {{ forloop.counter }}; --color:{{ color }} }
      {% endfor %}



      /*
      ul.cloud li:nth-child(2n+1) a { --color: #181; }
      ul.cloud li:nth-child(3n+1) a { --color: #33a; }
      ul.cloud li:nth-child(4n+1) a { --color: #c38; }
      */


      ul.cloud a:focus {
        outline: 1px dashed;
      }


      {% for color in colors %}
      ul.cloud a[data-weight="{{ forloop.counter }}"]::before {      
        content: "";
        position: absolute;
        top: 0;
        left: 50%;
        width: 0;
        height: 100%;
        background: {{ color }};
        transform: translate(-50%, 0);
        opacity: 0.15;
        transition: width 0.25s;
       }
      {% endfor %}

      ul.cloud a::before {
        /* ... Your existing styles ... */
        transition: all 0.3s ease;
    }

    ul.cloud a:hover::before {
      opacity: 0.25;
  }
      
/*      
      ul.cloud a::before {
        content: "";
        position: absolute;
        top: 0;
        left: 50%;
        width: 0;
        height: 100%;
        background: var(--color);
        transform: translate(-50%, 0);
        opacity: 0.15;
        transition: width 0.25s;
      }*/

      ul.cloud a:focus::before,
      ul.cloud a:hover::before {
        width: 100%;
      }
      
      @media (prefers-reduced-motion) {
        ul.cloud * {
          transition: none !important;
        }
      }
</style>

<ul class="cloud" role="navigation" aria-label="Webdev tag cloud">
{% for wc in wc_data %}
<li><a href="{{wc.url}}" data-weight="{{ wc.weight }}" title="{{ wc.short_url }}" target="_blank" rel="noopener noreferrer">{{ wc.alias }}</a></li>
{% endfor %}
</ul> 

<!-- 
<ul class="cloud" role="navigation" aria-label="Webdev tag cloud">
    <li><a data-weight="4" href="/tag/http">HTTP</a></li>
    <li><a data-weight="2" href="/tag/ember">Ember</a></li>
    <li><a data-weight="5" href="/tag/sass">Sass</a></li>
    <li><a data-weight="8" href="/tag/html">HTML</a></li>
    <li><a data-weight="6" href="/tag/flexbox">FlexBox</a></li>
    <li><a data-weight="4" href="/tag/api">API</a></li>
    <li><a data-weight="5" href="/tag/vuejs">VueJS</a></li>
    <li><a data-weight="6" href="/tag/grid">Grid</a></li>
    <li><a data-weight="3" href="/tag/rest">Rest</a></li>
    <li><a data-weight="9" href="/tag/javascript">JavaScript</a></li>
    <li><a data-weight="3" href="/tag/animation">Animation</a></li>
    <li><a data-weight="7" href="/tag/react">React</a></li>
    <li><a data-weight="8" href="/tag/css">CSS</a></li>
    <li><a data-weight="1" href="/tag/cache">Cache</a></li>
    <li><a data-weight="3" href="/tag/less">Less</a></li>
  </ul> -->


  {% block script %}

  {% endblock %}